### PR TITLE
fix unmarshal txl2

### LINKED ISSUE #1138: Panic when unmarshaling a apitypes.L2Tx
## Summary of Bug

Calling `json.Unmarshal(data, &transaction)` where transaction is type `apitypes.L2Tx` causes panic.
This is because of this https://github.com/hermeznetwork/hermez-node/blob/develop/common/apitypes/txl2.go#L145

### PR DESCRIPTION
**Pull request by ARR552**
Closes #1138

### What does this PR does?

This PR fix the unmarshal panic. Also add tests.

### How to test?

Run tests

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Include tests
- [X] Respect code style and lint
- [ ] Update swagger file (if needed)
- [ ] Update documentation (*.md) (if needed)

### CODE REVIEW

**Review by jeffprestes — DISMISSED** [review]

**Review by marioidival — DISMISSED** [review]

File: common/apitypes/txl2_test.go [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+	assert.NoError(t, err)
+}
+
+func TestUnmarshall(t *testing.T) {
+	var l2tx, dest TxL2
+	bytes, err := l2tx.MarshalJSON()
+	assert.NoError(t, err)
+	err = dest.UnmarshalJSON(bytes)
+	assert.NoError(t, err)
+}
```
Comment (arnaubennassar) [inline common/apitypes/txl2_test.go]: Suggestion: combine this two tests in a single one that:

1. Initialize a `TxL2` with some random data
2. Marshals the tx
3.  Unmarshals the tx
4. Assert that the unmarshaled tx has the same values as the marshaled one

**Review by arnaubennassar — CHANGES_REQUESTED** [review]

File: common/apitypes/txl2.go [hunk 2]
```diff
@@ -142,9 +144,92 @@ func (tx TxL2) MarshalJSON() ([]byte, error) {
 
 // UnmarshalJSON is used to create a TxL2 from JSON data
 func (tx *TxL2) UnmarshalJSON(data []byte) error {
-	err := json.Unmarshal(data, tx)
+	type jsonToken struct {
```
Comment (Mikelle) [inline common/apitypes/txl2.go:147]: Maybe it will be a little bit better to init struct outside of the function? And it seems, that token struct and jsonToken structs are the same. Is it really needed to have the same struct?

File: common/apitypes/txl2.go [hunk 3]
```diff
@@ -142,9 +144,92 @@ func (tx TxL2) MarshalJSON() ([]byte, error) {
...
+		RqToIdx              *HezIdx               `json:"requestToAccountIndex"`
+		RqToEthAddr          *HezEthAddr           `json:"requestToHezEthereumAddress"`
+		RqToBJJ              *HezBJJ               `json:"requestToBJJ"`
+		RqTokenID            *common.TokenID       `json:"requestTokenId"`
+		RqAmount             *BigIntStr            `json:"requestAmount"`
+		RqFee                *common.FeeSelector   `json:"requestFee"`
+		RqNonce              *nonce.Nonce          `json:"requestNonce"`
+		Token                jsonToken             `json:"token"`
+	}
+	var auxTx = jsonFormat{}
```
Comment (Mikelle) [inline common/apitypes/txl2.go]:
```suggestion
	var auxTx  jsonFormat
```
Or
```
auxTx := jsonFormat{}
```

**Review by arnaubennassar — DISMISSED** [review]

File: common/apitypes/txl2.go (hunk 2 above)
Comment (ARR552) [reply common/apitypes/txl2.go:147]: It is a intermediary struct. I think that it shouldn't be outside these functions because if not, everyone in the package could use it and it is worthless. Also, I've been checking the project and we do this in the same way as here.

Comment (ARR552) [reply common/apitypes/txl2.go:147]: If you still think that we shouldn't do it in this way, I can propose create a function that contains the struct and return an empty object with type jsonFormat. What do you think??

**Review by Mikelle — APPROVED** [review]
