### PR TITLE
atomic: fix error message at invalid group

### LINKED ISSUE #1040: Atomic group with invalid tx
## Summary of Bug

The transaction `info`, `error_code` and `error_type` in `txPool` in an invalid atomic group is incorrect. 

### Expected Behavior

if in an atomic group of 2 transactions there is an incorrect transaction, they should have the following information:
Correct tx: 
- info: `BatchNum X. unselectable atomic group  Y, tx Z failed due to: W`
- error_code: `18`,
- error_type: `ErrInvalidAtomicGroup`
Incorrect tx:
- info: `BatchNum X. W`
- error_code: `12`,
- error_type: `ErrNoCurrentNonce`

In this case the information is:
Correct tx: 
- info: `BatchNum: X.`
- error_code: `0`,
- error_type: ''
Incorrect tx: 
- info: `BatchNum X. unselectable atomic group  Y, tx Z failed due to: W`
- error_code: `12`,
- error_type: `ErrNoCurrentNonce`

### Steps to Reproduce
Send atomic group with 2 txs:
- one tx correct
- one tx incorrect: with `nonce > actualNonce` (for example)

### PR DESCRIPTION
**Pull request by marioidival**
Closes #1040
### What does this PR does?

Add properly message error to atomic group transactions.

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Include tests
- [X] Respect code style and lint
- [ ] Update swagger file (if needed)
- [ ] Update documentation (*.md) (if needed)

```
Starting test
    ✓ Init variables (4441ms)
    ✓ Check ETH L1 deposit (38350ms)
    ✓ Check ERC20 L1 deposit (44534ms)
    ✓ Check ETH L1 force exit (44260ms)
    ✓ Check ERC20 L1 force exit (48302ms)
    ✓ Check ETH withdrawal from firsts forceExits (16299ms)
    ✓ Check ERC20 withdrawal from firsts forceExits (12263ms)
    ✓ Check ETH N L1 force exits (38300ms)
    ✓ Check ETH withdrawal from previous N force exits (4107ms)
    ✓ Check single ETH L2 transfer (40267ms)
    ✓ Check single ERC20 L2 transfer (40212ms)
    ✓ Transfer ETH to a non-existent Bjj address (50324ms)
    ✓ Transfer ERC20 to a non-existent Bjj address (40313ms)
    ✓ Transfer ETH to hermez ethereum address (40327ms)
    ✓ Transfer ERC20 to hermez ethereum address (30195ms)
    ✓ Transfer ETH to non-existent ETH address (40334ms)
    ✓ Transfer ETH to hermez ethereum address from internal account (40239ms)
    ✓ Transfer ERC20 to hermez ethereum address from internal account (30208ms)
    ✓ Check multiple L2 ETH transfer in same batch (50779ms)
    ✓ Check multiple L2 ETH transfer in different batches (171580ms)
    ✓ Atomic txs (50478ms)


  21 passing (15m)
```

### CODE REVIEW

**Review by tclemos — DISMISSED** [review]

File: txselector/txselector.go [hunk 1]
```diff
@@ -1243,15 +1243,20 @@ func setInfoForFailedAtomicTx(
...
+	obj := common.TxSelectorError{
+		Message: fmt.Sprintf("unselectable atomic group"+" %s, tx %s failed due to: %s",
+			failedAtomicGroupID,
+			failedTxID,
+			failMessage.Message,
+		),
+		Code: ErrInvalidAtomicGroupCode,
+		Type: ErrInvalidAtomicGroupType,
+	}
+	return obj
```
Comment (arnaubennassar) [inline txselector/txselector.go:1261]:
```suggestion
	return common.TxSelectorError{
		Message: fmt.Sprintf("unselectable atomic group"+" %s, tx %s failed due to: %s",
			failedAtomicGroupID,
			failedTxID,
			failMessage.Message,
		),
		Code: ErrInvalidAtomicGroupCode,
		Type: ErrInvalidAtomicGroupType,
	}
```

**Review by arnaubennassar — APPROVED** [review]

**Review by arnaubennassar — APPROVED** [review]

**Review by jeffprestes — APPROVED** [review]

**Review by ARR552 — APPROVED** [review]
