### PR TITLE
Set more detailed info to non-selected atomic txs

### LINKED ISSUE #903: Add better logs for failed atomic txs
## Rationale

Set good tx.Info for failing atomic txs

### PR DESCRIPTION
**Pull request by arnaubennassar**
Closes #903 

### What does this PR does?

- Add info explaining why an atomic tx is not selected. It differentiates the tx that made the entire group fail from the others.

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Include tests
- [x] Respect code style and lint
- [ ] Update swagger file (if needed)
- [ ] Update documentation (*.md) (if needed)

### CODE REVIEW

**Review by mfcastellani — APPROVED** [review]

File: txselector/txselector.go [hunk 1]
```diff
@@ -144,6 +144,12 @@ func (txsel *TxSelector) GetL1L2TxSelection(selectionConfig txprocessor.Config,
 		discardedL2Txs, tracerr.Wrap(err)
 }
 
+type failedAtomicGroup struct {
```
Comment (tclemos) [inline txselector/txselector.go:147]: since this struct is meant to contain only one transaction from the atomic group, I suggest calling this as `failedAtomicTransaction`

File: go.mod [hunk 2]
```diff
@@ -30,10 +30,11 @@ require (
 	github.com/stretchr/testify v1.7.0
 	github.com/tyler-smith/go-bip39 v1.1.0 // indirect
 	github.com/urfave/cli/v2 v2.3.0
+	github.com/yourbasic/graph v0.0.0-20210606180040-8ecfec1c2869
```
Comment (tclemos) [inline go.mod:33]: this is an import used on `txspool.go`, but this PR is not affecting this specific file, so I'm not sure why this is being added at this moment, anyway, I just wanted to point this out because it is something weird to me.

**Review by tclemos — APPROVED** [review]
I'm approving it because I understand none of my comments will affect the functionality itself, just the way we make the code expressive and double-checking imports, also this is a merge to a WIP feature branch, saying that I understand we can handle these suggestions in the future.

File: txselector/txselector.go (hunk 1 above)
Comment (arnaubennassar) [reply txselector/txselector.go:147]: The `txID` is used to indicate the tx that made the entire group of txs fail. But the names I choose are not self explainatory, so I'll update this

File: go.mod (hunk 2 above)
Comment (arnaubennassar) [reply go.mod:33]: Yup it's wierd xD
I believe that at some point I didn't propagated something well, or made a branch with uncommited changes or something like that
