### PR TITLE
Fix 500 error code when fee is too low

### LINKED ISSUE #820: Return HTTP 500 status code in a bad request
When submit this TX to the node:

```json
{
    "id": "0x026d079fd299e67fc86ac8fa33a9529526eef9c290b7775a4ffa804b91281c5480",
    "type": "Transfer",
    "tokenId": 1,
    "fromAccountIndex": "hez:HEZ:21529",
    "toAccountIndex": "hez:HEZ:21541",
    "toHezEthereumAddress": "hez:0x263C3Ab7E4832eDF623fBdD66ACee71c028Ff591",
    "toBjj": "hez:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "amount": "900000000000000000",
    "fee": 200,
    "nonce": 18,
    "signature": "3cb79e84be6d63ac58f37f9ff3efbc4288d39ea54eb755fb958c5fe0eb33e7a6dacded5b68cb637f8e4bbb52883141f91709f30a5c0179e8aa762879bf9fc403"
}
```

It returns HTTP/500 but at the return the error message says

```json
{
    "Message": "tx.feeUSD (1513.56672) > maxFeeUSD (30)"
}
```

### Expected Behavior

It must return HTTP/400 status code

### Steps to Reproduce

Using Hermez-node Postman collection submit the JSON above to api.internaltestnet.hermez.io 

### Additional Information:

To test use Hermez internaltestnet - Goerli Ethereum network

### PR DESCRIPTION
**Pull request by ARR552**
Closes #820

### What does this PR does?

This PR fix the http error code when the tx fee sumited is too low or too high.

### How to test?

Send a tx with 0 fees (or a value below the minimum configurated in the hermez node) and check the http error code 400

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Include tests
- [X] Respect code style and lint
- [ ] Update swagger file (if needed)
- [ ] Update documentation (*.md) (if needed)

### CODE REVIEW

File: api/txspool.go [hunk 1]
```diff
@@ -48,6 +49,10 @@ func (a *API) postPoolTx(c *gin.Context) {
 	receivedTx.ClientIP = c.ClientIP()
 	// Insert to DB
 	if err := a.l2.AddTxAPI(&receivedTx); err != nil {
+		if strings.Contains(err.Error(), "tx.feeUSD") {
+			retBadReq(err, c)
```
Comment (Mikelle) [inline api/txspool.go:53]: Is the error returned there in a new apiError format?

**Review by arnaubennassar — APPROVED** [review]

**Review by Mikelle — APPROVED** [review]
