### PR TITLE
set min gas fee & convert gwei to wei before submit tx

### LINKED ISSUE #843: Gasprice from Etherscan is in gwei so it is needed to convert to wei
## Summary of Bug

The Etherscan API returns the gasprice value in gwei. However Ethereum nodes when process transaction uses wei. Hence, heznode was sending value very low and the forgeBatches was getting stuck at ethereum node transaction pool

### Expected Behavior

Converts Etherscan gasprice from gwei to wei

### Steps to Reproduce

it was detected by @jbaylina and @invocamanman in live and testnet environment.

### PR DESCRIPTION
**Pull request by jeffprestes**
Closes #843 . 

### What does this PR does?

It defines a min gas fee value to use to send tx to Ethereum (5 gwei - asked by @davidsrz , @invocamanman and @jbaylina ) and converts gas price from Etherscan API that comes in gwei format to wei format as wei format is the one used by Ethereum to post a transaction.

### How to test?

Forge a batch in an Ethereum testnet (rinkeby or goerli) . Local GETH or Ganache are not valid to be used in this test case. 

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Include tests
- [X] Respect code style and lint
- [ ] Update swagger file (if needed)
- [ ] Update documentation (*.md) (if needed)

PS.: As it were hurting the testnet this change was already applied at release/v1.3.0 branch and at v1.3.0-rc4 tag

### CODE REVIEW

File: coordinator/txmanager.go [hunk 1]
```diff
@@ -129,29 +130,36 @@ func (t *TxManager) syncSCVars(vars common.SCVariablesPtr) {
...
 			var er error
 			gasPrice, er = t.ethClient.EthSuggestGasPrice(ctx)
 			if er != nil {
 				return nil, tracerr.Wrap(er)
 			}
 		} else {
-			eGasPrice := new(big.Int)
-			eGasPrice, ok := eGasPrice.SetString(etherscanGasPrice.ProposeGasPrice, 10)
+			var ok bool
+			eGasPrice, ok = eGasPrice.SetString(etherscanGasPrice.ProposeGasPrice, 10)
```
Comment (ARR552) [inline coordinator/txmanager.go:155]: As sometimes the gas price is not enough, maybe we should use FastGasPrice instead of ProposeGasPrice. This option is expensive but the tx should always be mined. {"LastBlock":"12529900","SafeGasPrice":"19","ProposeGasPrice":"35","FastGasPrice":"42"}

**Review by ARR552 — APPROVED** [review]

**Review by arnaubennassar — APPROVED** [review]
