### PR TITLE
Reset pool txs with batchNum forged externally (alternative)

### LINKED ISSUE #718: L2Txs in forged state when batch fails but another node forges a batch with that batchnum
## Summary of Bug

When there are multiple coordinators the following can happen:
- Boot Coordinator starts forging a tx into a batch with BatchNum=N, and sends the batch to ethereum.
- Coordinator A forges an empty batch with BatchNum=N, and sends batch to ethereum.
- Batch from Boot Coordinator fails, batch from Coordinator A suceeds
- Boot Coordinator ends up with the tx marked as forged in the pool, but this tx was not forged in any "final" batch.

### Expected Behavior

If the batch forged by a coordinator is discarded, all the state changes in the pool regarding that batch should be discarded, even if there's another batch with the same batchNum by another coordinator

### Steps to Reproduce

Register an alternative coordinator and achieve the following:
- Both coordinators try to forge a batch with BatchNum=N at the same time, and only one suceeds.  The one that fails should have attempted to add an l2tx that the one that succeeds didn't have.

### Additional Information:

This bug affects the multi coordinator funcionality

### PR DESCRIPTION
**Pull request by ed255**
Alternative implementation of https://github.com/hermeznetwork/hermez-node/pull/719
Resolve #718

### CODE REVIEW

File: coordinator/coordinator.go [hunk 1]
```diff
@@ -490,6 +490,34 @@ func (c *Coordinator) handleMsgSyncBlock(ctx context.Context, msg *MsgSyncBlock)
...
+	externalBatchNums := []common.BatchNum{}
+	for _, batch := range msg.Batches {
+		if batch.Batch.ForgerAddr != c.cfg.ForgerAddress {
+			externalBatchNums = append(externalBatchNums, batch.Batch.BatchNum)
+		}
+	}
+	if len(externalBatchNums) > 0 {
+		// If we just synced external batches, make sure the pipeline
+		// is stopped
+		lastValidBatch := externalBatchNums[0] - 1
```
Comment (Pantani) [inline coordinator/coordinator.go:508]: Is this the last batch or only the last item of the slice? It's sorted by batch?

Comment (Pantani) [reply coordinator/coordinator.go:508]: I prefer this implementation, but Is it not better to use the lower batch for the reorg? I don't know how is this array is sorted

Comment (ed255) [reply coordinator/coordinator.go:508]: The batches in a block (which is the slice passed in `msg.Batches`) always appear sequentially, so the first one is the smallest one in the slice.
So Imagine an external coordinator forged batches 10, 11, 12. In `lastValidBatch` we store 9, and when doing the l2DB.Reorg(9), we are setting all the txs that we marked as non-pending (forging, invalid, forged} associated with batches {10, 11, 12, 13, etc...} back to pending pending.  Because we know that everything that we marked with a batchNum that has been forged externally will not end up in the real batch for that BatchNum, so we reset all the states we changed in those phantom batches we calculated.

**Review by Pantani — APPROVED** [review]
