### PR TITLE
Fix txselector L1CoordTxs

### LINKED ISSUE #866: Revert zki tests to match compatibility canary
## Rationale

- We should remain compatible with compatibility canary
- Once we're we will need to fix existing unit tests

### PR DESCRIPTION
**Pull request by arnaubennassar**
Close #866 

### What does this PR does?

- Revert the asserts of `test/zkproof/flows_test.go` so they match the ones in `compatibility-canary`
- When a coordinator creates accounts on behalf of the user, this transactions where grouped under `l1UserTxs` instead of `l1CoordTxs`, fixed it
- Added some `// TODO:` coments in part of the code that we should undertand better. They don't necessarily represent an actual request to change code, but just a pointer on stuff that we've to look deeper into it 

### How to test?

Unit tests now match `compatibility-canary` again

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Include tests
- [ ] Respect code style and lint
- [ ] Update swagger file (if needed)
- [ ] Update documentation (*.md) (if needed)

### CODE REVIEW

File: txselector/txselector.go [hunk 1]
```diff
@@ -122,6 +122,7 @@ func (s *TxSelector) getL1L2TxSelection(selectionConfig txprocessor.Config, l1Us
 	for _, tx := range l1UserTxs {
 		log.Debugw("TxSelector: processing L1 user tx", "TxID", tx.TxID.String())
 		// assumption: l1usertx are sorted by L1Tx.Position
+		// TODO: why is the output of the function ignored?
```
Comment (mfcastellani) [inline txselector/txselector.go:125]: From what I understand from the code these cases where the method output is ignored is when an error occurs, and then all parameters are returned as nil. My understanding is that this part is correct and can be kept that way, but I still lack a lot of business concept because I'm not even a month into the project, so my conclusion could be totally wrong.

Comment (arnaubennassar) [reply txselector/txselector.go:125]: After looking a bit into it, it seems that this method is called in other parts of the code where the output and input are not ignored. I believe this function is placed here in order to check if there is an error on the L1 txs and maybe it does some changes on the state. In any case I think that this is hard to understand, therefore I'd suggest to:

1. Understand exactly why is this method being called
2. Refactor a bit by
    a) Adding a description on what this does and why (go deeper than `// Process L1UserTxs`)
    b) Split the logic of the function `ProcessL1Tx` and give meaningful names

**Review by jeffprestes — APPROVED** [review]

**Review by mfcastellani — APPROVED** [review]
